---
- name: Checks that required variables are defined
  fail:
    msg: "Error: {{ item }} must be defined"
  when: item is not defined
  loop:
    - "{{ grafana_admin_user }}"
    - "{{ grafana_admin_password }}"
