---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grafana-bionic
    image: devopsworks/ubuntu-systemd:18.04
    image_version: latest
    privileged: true
  - name: grafana-xenial
    image: devopsworks/ubuntu-systemd:16.04
    image_version: latest
    privileged: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: inventory/group_vars/
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
